<?php $page = 'invoice-details-admin'; ?>
@extends('layout.mainlayout')

@section('content')
    <div class="page-wrapper invoice-admin-page">
        <div class="content container-fluid">
            <div class="page-header d-print-none">
                <div class="content-invoice-header">
                    <h5>Invoice Management: #{{ $sale->invoice_no ?? $sale->id }}</h5>
                    <div class="list-btn">
                        <ul class="filter-list">
                            <li>
                                <a href="{{ route('invoice-details-admin.print', ['id' => $sale->id]) }}" target="_blank" rel="noopener" class="btn btn-primary">
                                    <i class="fa fa-print me-2"></i> Print Invoice
                                </a>
                            </li>
                            <li>
                                <a href="{{ route('invoices.index') }}" class="btn btn-outline-secondary">
                                    <i class="fa fa-arrow-left me-2"></i> Back to List
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row g-4 align-items-start">
                <div class="col-xl-8 col-lg-8" id="printableArea" data-print-scope>
                    <div class="card shadow-sm border-0 invoice-print-shell">
                        <div class="card-body p-4 p-lg-5">
                            @include('Sales.Invoices.partials.invoice-detail-content')
                        </div>
                    </div>
                </div>

                <div class="col-xl-4 col-lg-4 d-print-none">
                    <div class="card timeline-card border-0 shadow-sm">
                        <div class="card-header bg-white">
                            <h6 class="card-title mb-0">Admin Controls</h6>
                        </div>
                        <div class="card-body">
                            <div class="mb-4">
                                <label class="form-label small fw-bold text-uppercase text-muted">Update Status</label>
                                <select class="form-control select">
                                    @foreach(['paid', 'unpaid', 'partially paid', 'overdue', 'cancelled'] as $status)
                                        <option value="{{ $status }}" {{ (($sale->effective_payment_status ?? $sale->payment_status) == $status) ? 'selected' : '' }}>
                                            {{ ucfirst($status) }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="p-3 bg-light rounded mb-4">
                                <h6 class="small fw-bold text-uppercase text-muted mb-3">Order Info</h6>
                                <div class="d-flex justify-content-between mb-2">
                                    <span class="text-muted">Reference:</span>
                                    <span class="fw-bold text-dark">{{ $sale->order_number ?? 'N/A' }}</span>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <span class="text-muted">Created:</span>
                                    <span class="text-dark">{{ $sale->created_at->diffForHumans() }}</span>
                                </div>
                            </div>

                            <h6 class="small fw-bold text-uppercase text-muted mb-3">Activity</h6>
                            <ul class="activity-feed list-unstyled small ps-2">
                                <li class="feed-item border-start ps-3 pb-3 position-relative">
                                    <span class="feed-text">Invoice generated by <strong>System</strong></span>
                                    <div class="text-muted smaller">{{ $sale->created_at->format('d M, h:i A') }}</div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <style>
        .activity-feed .feed-item::before {
            content: "";
            position: absolute;
            left: -5px;
            top: 0;
            width: 10px;
            height: 10px;
            background: #4b308b;
            border-radius: 50%;
        }

        .bg-light-soft {
            background-color: #fbfbfb;
        }

        @media print {
            @page {
                size: auto;
                margin: 8mm;
            }

            html,
            body {
                width: auto !important;
                min-width: 0 !important;
                max-width: none !important;
                overflow: visible !important;
                -webkit-print-color-adjust: exact !important;
                print-color-adjust: exact !important;
            }

            .page-header,
            .sidebar,
            .header,
            .btn,
            .d-print-none,
            .timeline-card,
            .main-wrapper > .sidebar,
            .main-wrapper > .header {
                display: none !important;
            }

            body,
            .page-wrapper,
            .content,
            .container-fluid,
            .row,
            #printableArea,
            .invoice-print-shell,
            .invoice-print-shell .card-body {
                margin: 0 !important;
                padding: 0 !important;
            }

            .page-wrapper {
                margin-left: 0 !important;
            }

            .row {
                display: block !important;
            }

            #printableArea {
                display: block !important;
                width: 100% !important;
                max-width: 100% !important;
                flex: none !important;
            }

            .invoice-print-shell {
                box-shadow: none !important;
                border: 0 !important;
                background: #fff !important;
            }

            .invoice-total-card { border: 1px solid #ddd !important; }
            .invoice-item-date.bg-light-soft { background-color: #f5f5f5 !important; print-color-adjust: exact; -webkit-print-color-adjust: exact; }
            .text-primary { color: #4b308b !important; print-color-adjust: exact; -webkit-print-color-adjust: exact; }
            thead tr th { background-color: #f8f9fa !important; color: #4b308b !important; print-color-adjust: exact; -webkit-print-color-adjust: exact; }
            tbody tr { background-color: #fcfcfc !important; print-color-adjust: exact; -webkit-print-color-adjust: exact; }
            .border-start.border-primary { border-left-color: #4b308b !important; print-color-adjust: exact; -webkit-print-color-adjust: exact; }
            .col-lg-5,
            .col-lg-7 {
                flex: 0 0 auto;
            }
        }

        @media print and (orientation: landscape) {
            @page {
                size: landscape;
                margin: 6mm;
            }

            .invoice-print-shell .card-body {
                padding: 2mm !important;
            }
        }
    </style>
@endsection
