<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $filing->name }} - Tax Workpaper</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #172033; font-size: 11px; }
        h1 { color: #073b76; font-size: 21px; margin-bottom: 4px; }
        h2 { color: #073b76; font-size: 14px; margin-top: 22px; }
        .meta { width: 100%; border-collapse: collapse; margin-top: 14px; }
        .meta td { padding: 5px 7px; border: 1px solid #d5deea; }
        .meta td:first-child { width: 25%; font-weight: bold; background: #eef4fb; }
        table.lines { width: 100%; border-collapse: collapse; }
        .lines th, .lines td { padding: 6px; border: 1px solid #d5deea; text-align: right; }
        .lines th { background: #073b76; color: #fff; }
        .lines th:first-child, .lines td:first-child { text-align: left; }
        .hash { margin-top: 24px; padding: 8px; background: #f3f6fa; word-break: break-all; font-size: 9px; }
        .muted { color: #5b6678; }
    </style>
</head>
<body>
    <h1>Tax Filing Workpaper</h1>
    <div class="muted">Generated by SmartProBook on {{ now()->format('d M Y, H:i') }}</div>

    <table class="meta">
        <tr><td>Filing</td><td>{{ $filing->name }}</td></tr>
        <tr><td>Authority</td><td>{{ $filing->jurisdiction?->tax_authority_name ?: $filing->jurisdiction?->name }}</td></tr>
        <tr><td>Country / Currency</td><td>{{ $filing->country_code }} / {{ $filing->currency_code }}</td></tr>
        <tr><td>Period</td><td>{{ $filing->period_start?->format('d M Y') }} to {{ $filing->period_end?->format('d M Y') }}</td></tr>
        <tr><td>Status / Reference</td><td>{{ ucfirst($filing->status) }} / {{ $filing->reference_no ?: 'Not filed' }}</td></tr>
        <tr><td>Approved</td><td>{{ $filing->approved_at?->format('d M Y, H:i') ?: 'Not approved' }}</td></tr>
    </table>

    <h2>Return Schedule</h2>
    <table class="lines">
        <thead><tr><th>Line</th><th>Taxable Base</th><th>Tax</th><th>Credit</th><th>Net</th></tr></thead>
        <tbody>
            @foreach($filing->lines as $line)
                <tr>
                    <td>{{ $line->label }}</td>
                    <td>{{ number_format((float) $line->taxable_base, 2) }}</td>
                    <td>{{ number_format((float) $line->tax_amount, 2) }}</td>
                    <td>{{ number_format((float) $line->credit_amount, 2) }}</td>
                    <td>{{ number_format((float) $line->net_amount, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <table class="meta">
        <tr><td>Total Taxable</td><td>{{ $filing->currency_code }} {{ number_format((float) $filing->total_taxable, 2) }}</td></tr>
        <tr><td>Tax Due</td><td>{{ $filing->currency_code }} {{ number_format((float) $filing->tax_due, 2) }}</td></tr>
        <tr><td>Tax Credit / Refund</td><td>{{ $filing->currency_code }} {{ number_format((float) $filing->tax_credit, 2) }} / {{ number_format((float) $filing->tax_refund, 2) }}</td></tr>
    </table>

    @if(data_get($filing->metadata, 'cit_workpaper'))
        @php($cit = data_get($filing->metadata, 'cit_workpaper'))
        <h2>Company Income Tax Computation</h2>
        <table class="meta">
            <tr><td>Accounting Profit</td><td>{{ number_format((float) data_get($cit, 'accounting_profit'), 2) }}</td></tr>
            <tr><td>Disallowable Expenses</td><td>{{ number_format((float) data_get($cit, 'disallowable_expenses'), 2) }}</td></tr>
            <tr><td>Loss Relief</td><td>({{ number_format((float) data_get($cit, 'loss_relief'), 2) }})</td></tr>
            <tr><td>Capital Allowances</td><td>({{ number_format((float) data_get($cit, 'capital_allowances'), 2) }})</td></tr>
            <tr><td>Taxable Profit</td><td>{{ number_format((float) data_get($cit, 'taxable_profit'), 2) }}</td></tr>
            <tr><td>Company Tax</td><td>{{ data_get($cit, 'cit_rate') }}% / {{ number_format((float) data_get($cit, 'gross_cit'), 2) }}</td></tr>
            <tr><td>Development Levy</td><td>{{ data_get($cit, 'development_levy_rate') }}% / {{ number_format((float) data_get($cit, 'development_levy'), 2) }}</td></tr>
            <tr><td>Credits</td><td>({{ number_format((float) data_get($cit, 'credits'), 2) }})</td></tr>
            <tr><td>Net Company Tax Due</td><td>{{ number_format((float) data_get($cit, 'net_cit_due'), 2) }}</td></tr>
        </table>
    @endif

    <div class="hash"><strong>Evidence package SHA-256:</strong> {{ $package['integrity_hash'] }}</div>
</body>
</html>
