<?php

$countries = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo',
    'Costa Rica',
    'Cote d\'Ivoire',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czechia',
    'Democratic Republic of the Congo',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Korea',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Korea',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
];

return [
    'countries' => $countries,
    'regions' => array_replace(array_fill_keys($countries, []), [
        'Nigeria' => [
            'FCT' => ['Abaji', 'AMAC', 'Bwari', 'Gwagwalada', 'Kuje', 'Kwali'],
            'Lagos' => ['Agege', 'Alimosho', 'Eti-Osa', 'Ikeja', 'Kosofe', 'Lagos Island', 'Lagos Mainland', 'Surulere'],
            'Rivers' => ['Port Harcourt', 'Obio-Akpor', 'Oyigbo', 'Eleme', 'Ikwerre'],
            'Kano' => ['Kano Municipal', 'Fagge', 'Nasarawa', 'Tarauni', 'Gwale'],
            'Kaduna' => ['Chikun', 'Kaduna North', 'Kaduna South', 'Igabi', 'Zaria'],
        ],
        'Ghana' => [
            'Greater Accra' => ['Accra Metropolitan', 'Adenta', 'Tema Metropolitan', 'Ga East', 'Ga West'],
            'Ashanti' => ['Kumasi Metropolitan', 'Obuasi Municipal', 'Ejisu'],
        ],
        'Kenya' => [
            'Nairobi County' => ['Westlands', 'Dagoretti North', 'Embakasi East', 'Starehe', 'Kasarani'],
            'Mombasa County' => ['Mvita', 'Nyali', 'Likoni', 'Changamwe', 'Jomvu'],
        ],
        'South Africa' => [
            'Gauteng' => ['Johannesburg', 'Tshwane', 'Ekurhuleni'],
            'Western Cape' => ['Cape Town', 'Stellenbosch', 'George'],
        ],
        'United Kingdom' => [
            'England' => ['Greater London', 'Manchester', 'Birmingham', 'Liverpool'],
            'Scotland' => ['Glasgow', 'Edinburgh', 'Aberdeen'],
        ],
        'United States' => [
            'California' => ['Los Angeles County', 'San Diego County', 'Santa Clara County'],
            'New York' => ['New York County', 'Kings County', 'Queens County'],
            'Texas' => ['Harris County', 'Dallas County', 'Travis County'],
        ],
        'Canada' => [
            'Ontario' => ['Toronto', 'Ottawa', 'Mississauga'],
            'Alberta' => ['Calgary', 'Edmonton', 'Red Deer'],
        ],
        'United Arab Emirates' => [
            'Dubai' => ['Deira', 'Bur Dubai', 'Jumeirah', 'Business Bay'],
            'Abu Dhabi' => ['Abu Dhabi City', 'Al Ain', 'Mussafah'],
        ],
    ]),
];
