@extends('layout.mainlayout')

@section('style')
<style>
    .farm-page{background:#f4f7f5;min-height:100vh;color:#14251b}.farm-hero{background:#123d2a;color:#fff;border-left:6px solid #f2b705;border-radius:6px;padding:18px 20px;display:flex;justify-content:space-between;gap:16px;align-items:center}.farm-hero h3{color:#fff;font-weight:900;margin:0}.farm-hero p{color:#d8eadf;margin:5px 0 0}.farm-actions{display:flex;gap:7px;flex-wrap:wrap}.farm-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.farm-kpi{background:#fff;border:1px solid #d7e3dc;border-radius:6px;padding:13px 15px;min-height:92px}.farm-kpi span{display:block;color:#607469;font-size:11px;font-weight:900;text-transform:uppercase}.farm-kpi strong{display:block;color:#123d2a;font-size:25px;line-height:1.2}.farm-kpi small{color:#6b7f73}.farm-kpi.gold{border-left:4px solid #e8aa00}.farm-kpi.red{border-left:4px solid #c83b31}.farm-kpi.blue{border-left:4px solid #1874b8}.farm-panel{background:#fff;border:1px solid #d7e3dc;border-radius:6px;overflow:hidden}.farm-panel-head{padding:13px 15px;border-bottom:1px solid #e3ebe6;display:flex;justify-content:space-between;gap:10px;align-items:center}.farm-panel-head h5{margin:0;font-weight:900;color:#123d2a}.farm-tabs{display:flex;gap:0;overflow-x:auto;border-bottom:1px solid #d7e3dc;background:#edf4f0}.farm-tabs button{border:0;border-right:1px solid #d7e3dc;background:transparent;padding:12px 16px;font-weight:800;white-space:nowrap;color:#385447}.farm-tabs button.active{background:#123d2a;color:#fff}.farm-tab{display:none}.farm-tab.active{display:block}.farm-table th{background:#edf4f0;color:#496255;text-transform:uppercase;font-size:11px;white-space:nowrap}.farm-table td{font-size:13px;vertical-align:middle}.farm-form{display:grid;gap:11px}.farm-form label{font-size:12px;font-weight:800;color:#50665a;margin-bottom:4px}.farm-form .form-control,.farm-form .form-select{min-height:40px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.margin-positive{color:#138247}.margin-negative{color:#c43131}.farm-empty{padding:42px 20px;text-align:center;color:#62776b}.farm-setup{max-width:720px;margin:25px auto;background:#fff;border:1px solid #d7e3dc;border-radius:6px;padding:22px}.metric-note{background:#f8fbf9;border:1px solid #dce7e0;padding:10px;border-radius:5px;font-size:12px;color:#50665a}.farm-filter{display:flex;gap:8px;flex-wrap:wrap;align-items:end}.farm-filter label{font-size:11px;font-weight:900;color:#d8eadf;display:block}.farm-filter .form-control,.farm-filter .form-select{min-height:38px}.modal-content{border-radius:6px}.modal-header{background:#123d2a;color:#fff}.modal-header .modal-title{color:#fff}.btn-close{filter:invert(1)}@media(max-width:1199px){.farm-kpis{grid-template-columns:repeat(2,1fr)}}@media(max-width:767px){.farm-hero{align-items:flex-start;flex-direction:column}.farm-kpis,.form-grid{grid-template-columns:1fr}.farm-filter{width:100%}}
</style>
@endsection

@section('content')
@php
    $money = fn($v) => \App\Support\GeoCurrency::format((float)$v, 'NGN', auth()->user()?->company?->currency_code, null);
    $label = fn($v) => ucwords(str_replace('_',' ',(string)$v));
@endphp
<div class="page-wrapper farm-page"><div class="content container-fluid">
    <section class="farm-hero mb-3">
        <div><h3>Layer Farm Cost & Production Centre</h3><p>Control flock performance, production cost, investment recovery and farm returns from one operating record.</p></div>
        @if($farm)<form method="GET" class="farm-filter"><div><label>Farm</label><select name="farm_id" class="form-select">@foreach($farms as $option)<option value="{{ $option->id }}" @selected($farm->id===$option->id)>{{ $option->name }}</option>@endforeach</select></div><div><label>From</label><input type="date" name="from" class="form-control" value="{{ $from }}"></div><div><label>To</label><input type="date" name="to" class="form-control" value="{{ $to }}"></div><button class="btn btn-warning"><i class="fas fa-filter me-1"></i> Apply</button></form>@endif
    </section>

    @if(!$farm)
        <section class="farm-setup"><h4 class="fw-bold">Set Up Your Layer Farm</h4><p class="text-muted">Create the operating unit before recording birds, investment and production.</p><form method="POST" action="{{ route('livestock.farms.store') }}" class="farm-form">@csrf<div class="form-grid"><div><label>Farm Name</label><input name="name" class="form-control" required placeholder="Sunrise Layer Farm"></div><div><label>Farm Code</label><input name="code" class="form-control" required placeholder="SLF-01"></div><div><label>Bird Capacity</label><input type="number" name="bird_capacity" min="1" class="form-control" required></div><div><label>Eggs per Crate</label><input type="number" name="eggs_per_crate" value="30" min="1" class="form-control" required></div></div><div><label>Location</label><input name="location" class="form-control"></div><button class="btn btn-success">Create Layer Farm</button></form></section>
    @else
        <div class="farm-kpis mb-3">
            <div class="farm-kpi blue"><span>Active Birds</span><strong>{{ number_format($summary['birds']) }}</strong><small>{{ number_format($farm->bird_capacity) }} farm capacity</small></div>
            <div class="farm-kpi"><span>Good Eggs</span><strong>{{ number_format($summary['good_eggs']) }}</strong><small>{{ number_format($summary['crates_equivalent'],2) }} crate equivalent</small></div>
            <div class="farm-kpi gold"><span>Hen-Day Production</span><strong>{{ number_format($summary['average_hen_day'],2) }}%</strong><small>{{ number_format($summary['damaged_eggs']) }} damaged eggs</small></div>
            <div class="farm-kpi red"><span>Mortality</span><strong>{{ number_format($summary['mortality']) }}</strong><small>{{ number_format($summary['feed_kg'],3) }} kg feed consumed</small></div>
            <div class="farm-kpi"><span>Capital Expenditure</span><strong>{{ $money($summary['capital_cost']) }}</strong><small>{{ $money($summary['capital_allocation']) }} depreciation to date</small></div>
            <div class="farm-kpi"><span>Working Capital</span><strong>{{ $money($summary['working_capital']) }}</strong><small>{{ $money($summary['working_allocation']) }} amortized to date</small></div>
            <div class="farm-kpi red"><span>Period Production Cost</span><strong>{{ $money($summary['opex']+$summary['period_allocation']) }}</strong><small>{{ $money($summary['cost_per_egg']) }} per good egg</small></div>
            <div class="farm-kpi {{ $summary['net_return'] >= 0 ? '' : 'red' }}"><span>Net Farm Return</span><strong class="{{ $summary['net_return'] >= 0 ? 'margin-positive' : 'margin-negative' }}">{{ $money($summary['net_return']) }}</strong><small>Revenue {{ $money($summary['revenue']) }}</small></div>
        </div>

        <div class="farm-actions mb-3">
            <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#newProduction"><i class="fas fa-egg me-1"></i> Daily Production</button>
            <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newFlock"><i class="fas fa-feather me-1"></i> New Flock</button>
            <button class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#newInvestment"><i class="fas fa-building me-1"></i> CAPEX / Working Capital</button>
            <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#newOpex"><i class="fas fa-receipt me-1"></i> Record OPEX</button>
            <button class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#newRevenue"><i class="fas fa-coins me-1"></i> Record Revenue</button>
            @if(Route::has('finance.fixed-assets.index'))<a href="{{ route('finance.fixed-assets.index') }}" class="btn btn-outline-dark"><i class="fas fa-calculator me-1"></i> Accounting Asset Register</a>@endif
            @if(Route::has('expenses.index'))<a href="{{ route('expenses.index') }}" class="btn btn-outline-danger"><i class="fas fa-book me-1"></i> Accounting Expenses</a>@endif
        </div>

        <section class="farm-panel">
            <nav class="farm-tabs" id="farmTabs"><button class="active" data-tab="production">Daily Production</button><button data-tab="investments">CAPEX & Working Capital</button><button data-tab="opex">Operating Expenses</button><button data-tab="revenue">Revenue</button><button data-tab="flocks">Flock Cycles</button></nav>
            <div class="farm-tab active" id="tab-production"><div class="farm-panel-head"><h5>Daily Production Register</h5><span class="badge bg-success">{{ $from }} to {{ $to }}</span></div><div class="table-responsive"><table class="table farm-table mb-0"><thead><tr><th>Date</th><th>Flock</th><th>Birds Open/Close</th><th>Mortality/Culls</th><th>Crates + Loose</th><th>Good/Damaged</th><th>Hen-Day</th><th>Feed</th><th>Health Notes</th><th></th></tr></thead><tbody>@forelse($productions as $row)<tr><td>{{ $row->production_date->format('d M Y') }}</td><td>{{ $row->flock?->batch_code }}</td><td>{{ number_format($row->opening_birds) }} / {{ number_format($row->closing_birds) }}</td><td>{{ $row->mortality }} / {{ $row->culled }}</td><td>{{ $row->egg_crates }} + {{ $row->loose_eggs }}</td><td>{{ number_format($row->total_good_eggs) }} / {{ $row->damaged_eggs }}</td><td class="fw-bold">{{ number_format($row->hen_day_percent,2) }}%</td><td>{{ number_format($row->feed_kg,3) }} kg</td><td><small>{{ $row->medication ?: 'No medication' }}<br>{{ $row->vaccination ?: 'No vaccination' }}</small></td><td><form method="POST" action="{{ route('livestock.production.destroy',$row) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" title="Delete"><i class="fas fa-trash"></i></button></form></td></tr>@empty<tr><td colspan="10" class="farm-empty">No production records in this period.</td></tr>@endforelse</tbody></table></div></div>
            <div class="farm-tab" id="tab-investments"><div class="farm-panel-head"><div><h5>Investment & Allocation Schedule</h5><small>Capital items depreciate; working capital items amortize over their selected useful life.</small></div></div><div class="table-responsive"><table class="table farm-table mb-0"><thead><tr><th>Class</th><th>Category</th><th>Description</th><th>Date</th><th>Original Cost</th><th>Life</th><th>Allocated to Date</th><th>Net Carrying Value</th><th></th></tr></thead><tbody>@forelse($investments as $row)@php $allocated=$row->allocationAsOf($to); @endphp<tr><td><span class="badge {{ $row->cost_class==='capital'?'bg-primary':'bg-warning text-dark' }}">{{ $label($row->cost_class) }}</span></td><td>{{ $label($row->category) }}</td><td>{{ $row->description }}</td><td>{{ $row->cost_date->format('d M Y') }}</td><td>{{ $money($row->cost) }}</td><td>{{ $row->useful_life_months }} months</td><td>{{ $money($allocated) }}</td><td class="fw-bold">{{ $money(max(0,$row->cost-$allocated)) }}</td><td><form method="POST" action="{{ route('livestock.investments.destroy',$row) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="fas fa-trash"></i></button></form></td></tr>@empty<tr><td colspan="9" class="farm-empty">No capital or working-capital records yet.</td></tr>@endforelse</tbody></table></div></div>
            <div class="farm-tab" id="tab-opex"><div class="farm-panel-head"><h5>Recurrent Direct Production Cost</h5><strong>{{ $money($summary['opex']) }}</strong></div><div class="table-responsive"><table class="table farm-table mb-0"><thead><tr><th>Date</th><th>Category</th><th>Flock</th><th>Description</th><th>Quantity</th><th>Frequency</th><th>Vendor</th><th>Amount</th><th></th></tr></thead><tbody>@forelse($opex as $row)<tr><td>{{ $row->expense_date->format('d M Y') }}</td><td>{{ $label($row->category) }}</td><td>{{ $row->flock?->batch_code ?? 'General' }}</td><td>{{ $row->description ?: '-' }}</td><td>{{ $row->quantity }} {{ $row->unit }}</td><td>{{ ucfirst($row->frequency) }}</td><td>{{ $row->vendor ?: '-' }}</td><td class="fw-bold">{{ $money($row->amount) }}</td><td><form method="POST" action="{{ route('livestock.opex.destroy',$row) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="fas fa-trash"></i></button></form></td></tr>@empty<tr><td colspan="9" class="farm-empty">No operating expenses in this period.</td></tr>@endforelse</tbody></table></div></div>
            <div class="farm-tab" id="tab-revenue"><div class="farm-panel-head"><div><h5>Farm Revenue Register</h5><small>Eggs, culled layers, manure/litter and used feed bags.</small></div><strong>{{ $money($summary['revenue']) }}</strong></div><div class="table-responsive"><table class="table farm-table mb-0"><thead><tr><th>Date</th><th>Source</th><th>Flock</th><th>Customer</th><th>Description</th><th>Quantity</th><th>Unit Price</th><th>Amount</th><th></th></tr></thead><tbody>@forelse($revenue as $row)<tr><td>{{ $row->revenue_date->format('d M Y') }}</td><td>{{ $label($row->source) }}</td><td>{{ $row->flock?->batch_code ?? 'General' }}</td><td>{{ $row->customer ?: 'Walk-in' }}</td><td>{{ $row->description ?: '-' }}</td><td>{{ $row->quantity }} {{ $row->unit }}</td><td>{{ $money($row->unit_price) }}</td><td class="fw-bold text-success">{{ $money($row->amount) }}</td><td><form method="POST" action="{{ route('livestock.revenue.destroy',$row) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="fas fa-trash"></i></button></form></td></tr>@empty<tr><td colspan="9" class="farm-empty">No farm revenue in this period.</td></tr>@endforelse</tbody></table></div></div>
            <div class="farm-tab" id="tab-flocks"><div class="farm-panel-head"><h5>Layer Flock Cycles</h5><span class="badge bg-primary">{{ $flocks->where('status','active')->count() }} active</span></div><div class="table-responsive"><table class="table farm-table mb-0"><thead><tr><th>Batch</th><th>Breed</th><th>Placement</th><th>Placement Age</th><th>Opening Birds</th><th>Current Birds</th><th>Bird Cost</th><th>Acquisition Cost</th><th>Status</th></tr></thead><tbody>@forelse($flocks as $row)<tr><td class="fw-bold">{{ $row->batch_code }}</td><td>{{ $row->breed ?: '-' }}</td><td>{{ $row->placement_date->format('d M Y') }}</td><td>{{ $row->age_at_placement_weeks }} weeks</td><td>{{ number_format($row->opening_birds) }}</td><td>{{ number_format($row->current_birds) }}</td><td>{{ $money($row->cost_per_bird) }}</td><td>{{ $money($row->opening_birds*$row->cost_per_bird) }}</td><td><span class="badge bg-success">{{ ucfirst($row->status) }}</span></td></tr>@empty<tr><td colspan="9" class="farm-empty">No flock cycle has been opened.</td></tr>@endforelse</tbody></table></div></div>
        </section>

        @include('livestock.partials.entry-modals', compact('farm','flocks'))
    @endif
</div></div>
@endsection

@section('script')
<script>document.querySelectorAll('#farmTabs button').forEach(function(button){button.addEventListener('click',function(){document.querySelectorAll('#farmTabs button').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.farm-tab').forEach(t=>t.classList.remove('active'));button.classList.add('active');document.getElementById('tab-'+button.dataset.tab).classList.add('active');});});document.querySelectorAll('[data-calc-total]').forEach(function(form){const q=form.querySelector('[name=quantity]'),p=form.querySelector('[name=unit_cost], [name=unit_price]'),a=form.querySelector('[name=amount]');function calc(){if(q&&p&&a)a.value=(Number(q.value||0)*Number(p.value||0)).toFixed(2)}q?.addEventListener('input',calc);p?.addEventListener('input',calc);});</script>
@endsection
