<div style="font-family: sans-serif; padding: 20px;">
    <h2 style="color: #1b2559;">Inventory Reorder Alert</h2>
    <p>The system has identified items that have fallen below the threshold.</p>
    <p>Please find the attached <strong>Low Stock Report</strong> for immediate processing.</p>
    <br>
    <p style="font-size: 12px; color: #777;">Generated by SMAT ERP System.</p>
</div>