<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $subject }}</title>
    <style>
        body {
            font-family: DejaVu Sans, Arial, sans-serif;
            font-size: 13px;
            color: #1f2937;
            margin: 28px;
            line-height: 1.6;
        }
        .header {
            border-bottom: 2px solid #2563eb;
            padding-bottom: 12px;
            margin-bottom: 22px;
        }
        .brand {
            font-size: 11px;
            letter-spacing: 0.12em;
            text-transform: uppercase;
            color: #64748b;
            margin-bottom: 8px;
        }
        .title {
            font-size: 24px;
            font-weight: 700;
            color: #0f172a;
            margin: 0 0 8px;
        }
        .meta {
            font-size: 11px;
            color: #475569;
        }
        .summary {
            background: #f8fafc;
            border: 1px solid #dbeafe;
            border-radius: 8px;
            padding: 16px;
        }
        .summary-label {
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 0.08em;
            color: #2563eb;
            margin-bottom: 10px;
        }
        .body {
            white-space: pre-wrap;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="brand">SmartProbook Report Delivery</div>
        <h1 class="title">{{ $subject }}</h1>
        <div class="meta">
            Generated by {{ $generatedBy }} on {{ $generatedAt->format('d M Y h:i A') }}
        </div>
    </div>

    <div class="summary">
        <div class="summary-label">Report Summary</div>
        <div class="body">{{ $body }}</div>
    </div>
</body>
</html>
