<?php

namespace App\Support;

class TaxCountryCatalog
{
    public static function supportedCountries(): array
    {
        return [
            'DZA' => ['name' => 'Algeria', 'currency' => 'DZD', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'AGO' => ['name' => 'Angola', 'currency' => 'AOA', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 30],
            'ARG' => ['name' => 'Argentina', 'currency' => 'ARS', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'AUS' => ['name' => 'Australia', 'currency' => 'AUD', 'filing_frequency' => 'quarterly', 'filing_deadline_days' => 28],
            'AUT' => ['name' => 'Austria', 'currency' => 'EUR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'BHR' => ['name' => 'Bahrain', 'currency' => 'BHD', 'filing_frequency' => 'quarterly', 'filing_deadline_days' => 30],
            'BEL' => ['name' => 'Belgium', 'currency' => 'EUR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'BEN' => ['name' => 'Benin', 'currency' => 'XOF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'BWA' => ['name' => 'Botswana', 'currency' => 'BWP', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 25],
            'BRA' => ['name' => 'Brazil', 'currency' => 'BRL', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'BFA' => ['name' => 'Burkina Faso', 'currency' => 'XOF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'BDI' => ['name' => 'Burundi', 'currency' => 'BIF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'CMR' => ['name' => 'Cameroon', 'currency' => 'XAF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'CAN' => ['name' => 'Canada', 'currency' => 'CAD', 'filing_frequency' => 'quarterly', 'filing_deadline_days' => 30],
            'CPV' => ['name' => 'Cape Verde', 'currency' => 'CVE', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'CAF' => ['name' => 'Central African Republic', 'currency' => 'XAF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'TCD' => ['name' => 'Chad', 'currency' => 'XAF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'CHL' => ['name' => 'Chile', 'currency' => 'CLP', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'CHN' => ['name' => 'China', 'currency' => 'CNY', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'COL' => ['name' => 'Colombia', 'currency' => 'COP', 'filing_frequency' => 'bimonthly', 'filing_deadline_days' => 20],
            'COM' => ['name' => 'Comoros', 'currency' => 'KMF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'COD' => ['name' => 'Congo, Democratic Republic', 'currency' => 'CDF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'COG' => ['name' => 'Congo, Republic', 'currency' => 'XAF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'CIV' => ['name' => "Cote d'Ivoire", 'currency' => 'XOF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'HRV' => ['name' => 'Croatia', 'currency' => 'EUR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'CYP' => ['name' => 'Cyprus', 'currency' => 'EUR', 'filing_frequency' => 'quarterly', 'filing_deadline_days' => 40],
            'CZE' => ['name' => 'Czech Republic', 'currency' => 'CZK', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 25],
            'DNK' => ['name' => 'Denmark', 'currency' => 'DKK', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 25],
            'DJI' => ['name' => 'Djibouti', 'currency' => 'DJF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'EGY' => ['name' => 'Egypt', 'currency' => 'EGP', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 30],
            'GNQ' => ['name' => 'Equatorial Guinea', 'currency' => 'XAF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'ERI' => ['name' => 'Eritrea', 'currency' => 'ERN', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'EST' => ['name' => 'Estonia', 'currency' => 'EUR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'ETH' => ['name' => 'Ethiopia', 'currency' => 'ETB', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 30],
            'FIN' => ['name' => 'Finland', 'currency' => 'EUR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 12],
            'FRA' => ['name' => 'France', 'currency' => 'EUR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 24],
            'GAB' => ['name' => 'Gabon', 'currency' => 'XAF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'GMB' => ['name' => 'Gambia', 'currency' => 'GMD', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'DEU' => ['name' => 'Germany', 'currency' => 'EUR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 10],
            'GHA' => ['name' => 'Ghana', 'currency' => 'GHS', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 30],
            'GRC' => ['name' => 'Greece', 'currency' => 'EUR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 30],
            'GIN' => ['name' => 'Guinea', 'currency' => 'GNF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'GNB' => ['name' => 'Guinea-Bissau', 'currency' => 'XOF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'HKG' => ['name' => 'Hong Kong', 'currency' => 'HKD', 'filing_frequency' => 'bimonthly', 'filing_deadline_days' => 15],
            'HUN' => ['name' => 'Hungary', 'currency' => 'HUF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'IND' => ['name' => 'India', 'currency' => 'INR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'IDN' => ['name' => 'Indonesia', 'currency' => 'IDR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'IRL' => ['name' => 'Ireland', 'currency' => 'EUR', 'filing_frequency' => 'bimonthly', 'filing_deadline_days' => 23],
            'ISR' => ['name' => 'Israel', 'currency' => 'ILS', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'ITA' => ['name' => 'Italy', 'currency' => 'EUR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 16],
            'JPN' => ['name' => 'Japan', 'currency' => 'JPY', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 30],
            'KEN' => ['name' => 'Kenya', 'currency' => 'KES', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'KWT' => ['name' => 'Kuwait', 'currency' => 'KWD', 'filing_frequency' => 'quarterly', 'filing_deadline_days' => 30],
            'LVA' => ['name' => 'Latvia', 'currency' => 'EUR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'LBN' => ['name' => 'Lebanon', 'currency' => 'LBP', 'filing_frequency' => 'quarterly', 'filing_deadline_days' => 20],
            'LSO' => ['name' => 'Lesotho', 'currency' => 'LSL', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'LBR' => ['name' => 'Liberia', 'currency' => 'LRD', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'LBY' => ['name' => 'Libya', 'currency' => 'LYD', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 30],
            'LTU' => ['name' => 'Lithuania', 'currency' => 'EUR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 25],
            'LUX' => ['name' => 'Luxembourg', 'currency' => 'EUR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'MDG' => ['name' => 'Madagascar', 'currency' => 'MGA', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'MWI' => ['name' => 'Malawi', 'currency' => 'MWK', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 14],
            'MYS' => ['name' => 'Malaysia', 'currency' => 'MYR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 30],
            'MLI' => ['name' => 'Mali', 'currency' => 'XOF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'MLT' => ['name' => 'Malta', 'currency' => 'EUR', 'filing_frequency' => 'quarterly', 'filing_deadline_days' => 45],
            'MRT' => ['name' => 'Mauritania', 'currency' => 'MRU', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'MUS' => ['name' => 'Mauritius', 'currency' => 'MUR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'MEX' => ['name' => 'Mexico', 'currency' => 'MXN', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 17],
            'MAR' => ['name' => 'Morocco', 'currency' => 'MAD', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'MOZ' => ['name' => 'Mozambique', 'currency' => 'MZN', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'NAM' => ['name' => 'Namibia', 'currency' => 'NAD', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'NLD' => ['name' => 'Netherlands', 'currency' => 'EUR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 30],
            'NZL' => ['name' => 'New Zealand', 'currency' => 'NZD', 'filing_frequency' => 'bimonthly', 'filing_deadline_days' => 28],
            'NER' => ['name' => 'Niger', 'currency' => 'XOF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'NGA' => ['name' => 'Nigeria', 'currency' => 'NGN', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 21],
            'NOR' => ['name' => 'Norway', 'currency' => 'NOK', 'filing_frequency' => 'bimonthly', 'filing_deadline_days' => 10],
            'OMN' => ['name' => 'Oman', 'currency' => 'OMR', 'filing_frequency' => 'quarterly', 'filing_deadline_days' => 30],
            'PAK' => ['name' => 'Pakistan', 'currency' => 'PKR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'PER' => ['name' => 'Peru', 'currency' => 'PEN', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'PHL' => ['name' => 'Philippines', 'currency' => 'PHP', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 25],
            'POL' => ['name' => 'Poland', 'currency' => 'PLN', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 25],
            'PRT' => ['name' => 'Portugal', 'currency' => 'EUR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'QAT' => ['name' => 'Qatar', 'currency' => 'QAR', 'filing_frequency' => 'quarterly', 'filing_deadline_days' => 30],
            'ROU' => ['name' => 'Romania', 'currency' => 'RON', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 25],
            'RUS' => ['name' => 'Russia', 'currency' => 'RUB', 'filing_frequency' => 'quarterly', 'filing_deadline_days' => 25],
            'RWA' => ['name' => 'Rwanda', 'currency' => 'RWF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'STP' => ['name' => 'Sao Tome and Principe', 'currency' => 'STN', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'SAU' => ['name' => 'Saudi Arabia', 'currency' => 'SAR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 30],
            'SEN' => ['name' => 'Senegal', 'currency' => 'XOF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'SRB' => ['name' => 'Serbia', 'currency' => 'RSD', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'SYC' => ['name' => 'Seychelles', 'currency' => 'SCR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 21],
            'SLE' => ['name' => 'Sierra Leone', 'currency' => 'SLL', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'SGP' => ['name' => 'Singapore', 'currency' => 'SGD', 'filing_frequency' => 'quarterly', 'filing_deadline_days' => 30],
            'SVK' => ['name' => 'Slovakia', 'currency' => 'EUR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 25],
            'SVN' => ['name' => 'Slovenia', 'currency' => 'EUR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 30],
            'SOM' => ['name' => 'Somalia', 'currency' => 'SOS', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'ZAF' => ['name' => 'South Africa', 'currency' => 'ZAR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 25],
            'SSD' => ['name' => 'South Sudan', 'currency' => 'SSP', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'ESP' => ['name' => 'Spain', 'currency' => 'EUR', 'filing_frequency' => 'quarterly', 'filing_deadline_days' => 20],
            'LKA' => ['name' => 'Sri Lanka', 'currency' => 'LKR', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'SDN' => ['name' => 'Sudan', 'currency' => 'SDG', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'SWZ' => ['name' => 'Eswatini', 'currency' => 'SZL', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'SWE' => ['name' => 'Sweden', 'currency' => 'SEK', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 26],
            'CHE' => ['name' => 'Switzerland', 'currency' => 'CHF', 'filing_frequency' => 'quarterly', 'filing_deadline_days' => 60],
            'TWN' => ['name' => 'Taiwan', 'currency' => 'TWD', 'filing_frequency' => 'bimonthly', 'filing_deadline_days' => 15],
            'TZA' => ['name' => 'Tanzania', 'currency' => 'TZS', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'THA' => ['name' => 'Thailand', 'currency' => 'THB', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'TGO' => ['name' => 'Togo', 'currency' => 'XOF', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 18],
            'TUN' => ['name' => 'Tunisia', 'currency' => 'TND', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 28],
            'TUR' => ['name' => 'Turkey', 'currency' => 'TRY', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 26],
            'UGA' => ['name' => 'Uganda', 'currency' => 'UGX', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'UKR' => ['name' => 'Ukraine', 'currency' => 'UAH', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'GBR' => ['name' => 'United Kingdom', 'currency' => 'GBP', 'filing_frequency' => 'quarterly', 'filing_deadline_days' => 30],
            'ARE' => ['name' => 'United Arab Emirates', 'currency' => 'AED', 'filing_frequency' => 'quarterly', 'filing_deadline_days' => 28],
            'USA' => ['name' => 'United States', 'currency' => 'USD', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 30],
            'URY' => ['name' => 'Uruguay', 'currency' => 'UYU', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 25],
            'VEN' => ['name' => 'Venezuela', 'currency' => 'VES', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 15],
            'VNM' => ['name' => 'Vietnam', 'currency' => 'VND', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 20],
            'ZMB' => ['name' => 'Zambia', 'currency' => 'ZMW', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 18],
            'ZWE' => ['name' => 'Zimbabwe', 'currency' => 'USD', 'filing_frequency' => 'monthly', 'filing_deadline_days' => 25],
        ];
    }

    public static function presetCountries(): array
    {
        return array_intersect_key(self::supportedCountries(), array_flip(['NGA', 'USA']));
    }

    public static function presetsFor(string $countryCode): ?array
    {
        return match (strtoupper($countryCode)) {
            'NGA' => self::nigeriaPresets(),
            'USA' => self::unitedStatesPresets(),
            default => null,
        };
    }

    public static function nigeriaPresets(): array
    {
        return [
            'jurisdiction' => [
                'name' => 'Nigeria Federal Tax',
                'country_code' => 'NGA',
                'region' => 'Federal',
                'currency_code' => 'NGN',
                'filing_frequency' => 'monthly',
                'filing_deadline_days' => 21,
                'tax_authority_name' => 'Nigeria Revenue Service',
                'registration_threshold' => 25000000,
                'portal_url' => 'https://selfservice.nrs.gov.ng/',
                'metadata' => [
                    'supports_atrs' => true,
                    'default_reverse_charge' => false,
                    'jurisdiction_level' => 'federal',
                    'regulatory_status' => 'verified',
                    'reviewed_on' => '2026-10-02',
                    'effective_framework_from' => '2026-01-01',
                    'sources' => [
                        'https://www.nrs.gov.ng/tax-laws/nrs-act',
                        'https://www.nrs.gov.ng/tax-information/value-added-tax',
                        'https://einvoice.nrs.gov.ng/docs/system-integrator/invoice-schema',
                    ],
                ],
            ],
            'tax_codes' => [
                [
                    'code' => 'NGA-VAT-STD',
                    'name' => 'Nigeria VAT',
                    'description' => 'Nigeria standard VAT',
                    'type' => 'vat',
                    'category' => 'indirect',
                    'rate' => 7.5,
                    'calculation_method' => 'exclusive',
                    'filing_frequency' => 'monthly',
                    'filing_deadline_days' => 21,
                    'report_template' => 'nigeria-vat',
                    'ledger_output_account_code' => 'OUTPUT-VAT',
                    'ledger_input_account_code' => 'INPUT-VAT',
                    'ledger_payable_account_code' => 'VAT-PAYABLE',
                    'ledger_receivable_account_code' => 'VAT-RECEIVABLE',
                    'registration_threshold' => 25000000,
                    'applies_to' => ['sales', 'purchases', 'expenses', 'credit_notes', 'debit_notes'],
                    'metadata' => ['firs_tag' => 'vat_standard'],
                ],
                [
                    'code' => 'NGA-VAT-ZERO',
                    'name' => 'Nigeria VAT Zero Rated',
                    'description' => 'Nigeria zero-rated VAT supplies',
                    'type' => 'vat',
                    'category' => 'indirect',
                    'rate' => 0,
                    'calculation_method' => 'exclusive',
                    'filing_frequency' => 'monthly',
                    'filing_deadline_days' => 21,
                    'report_template' => 'nigeria-vat',
                    'ledger_output_account_code' => 'OUTPUT-VAT',
                    'ledger_payable_account_code' => 'VAT-PAYABLE',
                    'is_zero_rated' => true,
                    'applies_to' => ['sales'],
                    'metadata' => ['firs_tag' => 'vat_zero'],
                ],
                [
                    'code' => 'NGA-VAT-EXEMPT',
                    'name' => 'Nigeria VAT Exempt',
                    'description' => 'Nigeria VAT exempt supplies',
                    'type' => 'vat',
                    'category' => 'indirect',
                    'rate' => 0,
                    'calculation_method' => 'exclusive',
                    'filing_frequency' => 'monthly',
                    'filing_deadline_days' => 21,
                    'report_template' => 'nigeria-vat',
                    'is_exempt' => true,
                    'applies_to' => ['sales', 'purchases'],
                    'metadata' => ['firs_tag' => 'vat_exempt'],
                ],
                [
                    'code' => 'NGA-STAMP-DUTY',
                    'name' => 'Nigeria Stamp Duty',
                    'description' => 'Stamp duty on eligible transactions',
                    'type' => 'stamp_duty',
                    'category' => 'levy',
                    'rate' => 0,
                    'calculation_method' => 'exclusive',
                    'ledger_payable_account_code' => 'STAMP-DUTY-PAYABLE',
                    'ledger_expense_account_code' => 'STAMP-DUTY-EXPENSE',
                    'applies_to' => ['sales', 'receipts'],
                    'metadata' => ['threshold' => 10000],
                ],
                [
                    'code' => 'NGA-CIT-PROVISION',
                    'name' => 'Nigeria Corporate Income Tax Provision',
                    'description' => 'Estimated corporate tax provision',
                    'type' => 'corporate_income_tax',
                    'category' => 'direct',
                    'rate' => 30,
                    'calculation_method' => 'exclusive',
                    'filing_frequency' => 'annual',
                    'filing_deadline_days' => 180,
                    'ledger_payable_account_code' => 'CIT-PAYABLE',
                    'ledger_expense_account_code' => 'TAX-EXPENSE',
                    'applies_to' => ['manual_journal', 'period_close'],
                    'metadata' => ['estimated_only' => true],
                ],
            ],
            'withholding_rules' => [
                ['name' => 'Professional Services WHT', 'service_type' => 'professional_services', 'counterparty_type' => 'vendor', 'rate' => 10, 'threshold_amount' => 0, 'account_code' => 'WHT-PAYABLE', 'payable_account_code' => 'WHT-PAYABLE', 'receivable_account_code' => 'WHT-RECEIVABLE', 'certificate_prefix' => 'WHT-PRO'],
                ['name' => 'Consultancy WHT', 'service_type' => 'consultancy', 'counterparty_type' => 'vendor', 'rate' => 10, 'threshold_amount' => 0, 'account_code' => 'WHT-PAYABLE', 'payable_account_code' => 'WHT-PAYABLE', 'receivable_account_code' => 'WHT-RECEIVABLE', 'certificate_prefix' => 'WHT-CON'],
                ['name' => 'Management Fees WHT', 'service_type' => 'management_services', 'counterparty_type' => 'vendor', 'rate' => 10, 'threshold_amount' => 0, 'account_code' => 'WHT-PAYABLE', 'payable_account_code' => 'WHT-PAYABLE', 'receivable_account_code' => 'WHT-RECEIVABLE', 'certificate_prefix' => 'WHT-MGT'],
                ['name' => 'Commissions WHT', 'service_type' => 'commissions', 'counterparty_type' => 'vendor', 'rate' => 10, 'threshold_amount' => 0, 'account_code' => 'WHT-PAYABLE', 'payable_account_code' => 'WHT-PAYABLE', 'receivable_account_code' => 'WHT-RECEIVABLE', 'certificate_prefix' => 'WHT-COM'],
                ['name' => 'Directors Fees WHT', 'service_type' => 'directors_fees', 'counterparty_type' => 'vendor', 'rate' => 10, 'threshold_amount' => 0, 'account_code' => 'WHT-PAYABLE', 'payable_account_code' => 'WHT-PAYABLE', 'receivable_account_code' => 'WHT-RECEIVABLE', 'certificate_prefix' => 'WHT-DIR'],
                ['name' => 'Contracts WHT', 'service_type' => 'contracts', 'counterparty_type' => 'vendor', 'rate' => 5, 'threshold_amount' => 0, 'account_code' => 'WHT-PAYABLE', 'payable_account_code' => 'WHT-PAYABLE', 'receivable_account_code' => 'WHT-RECEIVABLE', 'certificate_prefix' => 'WHT-CONTRACT'],
                ['name' => 'Construction WHT', 'service_type' => 'construction', 'counterparty_type' => 'vendor', 'rate' => 5, 'threshold_amount' => 0, 'account_code' => 'WHT-PAYABLE', 'payable_account_code' => 'WHT-PAYABLE', 'receivable_account_code' => 'WHT-RECEIVABLE', 'certificate_prefix' => 'WHT-BUILD'],
                ['name' => 'Rent WHT', 'service_type' => 'rent', 'counterparty_type' => 'vendor', 'rate' => 10, 'threshold_amount' => 0, 'account_code' => 'WHT-PAYABLE', 'payable_account_code' => 'WHT-PAYABLE', 'receivable_account_code' => 'WHT-RECEIVABLE', 'certificate_prefix' => 'WHT-RENT'],
            ],
            'account_mappings' => [
                ['tax_type' => 'vat', 'role' => 'output_vat', 'account_code' => 'OUTPUT-VAT', 'account_name' => 'Output VAT'],
                ['tax_type' => 'vat', 'role' => 'input_vat', 'account_code' => 'INPUT-VAT', 'account_name' => 'Input VAT'],
                ['tax_type' => 'vat', 'role' => 'vat_payable', 'account_code' => 'VAT-PAYABLE', 'account_name' => 'VAT Payable'],
                ['tax_type' => 'vat', 'role' => 'vat_receivable', 'account_code' => 'VAT-RECEIVABLE', 'account_name' => 'VAT Receivable'],
                ['tax_type' => 'withholding', 'role' => 'wht_payable', 'account_code' => 'WHT-PAYABLE', 'account_name' => 'Withholding Tax Payable'],
                ['tax_type' => 'withholding', 'role' => 'wht_receivable', 'account_code' => 'WHT-RECEIVABLE', 'account_name' => 'Withholding Tax Receivable'],
                ['tax_type' => 'paye', 'role' => 'paye_payable', 'account_code' => 'PAYE-PAYABLE', 'account_name' => 'PAYE Payable'],
                ['tax_type' => 'corporate_income_tax', 'role' => 'tax_payable', 'account_code' => 'CIT-PAYABLE', 'account_name' => 'Corporate Income Tax Payable'],
                ['tax_type' => 'corporate_income_tax', 'role' => 'tax_expense', 'account_code' => 'TAX-EXPENSE', 'account_name' => 'Tax Expense'],
                ['tax_type' => 'deferred_tax', 'role' => 'deferred_tax', 'account_code' => 'DEFERRED-TAX', 'account_name' => 'Deferred Tax'],
                ['tax_type' => 'stamp_duty', 'role' => 'stamp_duty_payable', 'account_code' => 'STAMP-DUTY-PAYABLE', 'account_name' => 'Stamp Duty Payable'],
            ],
        ];
    }

    public static function unitedStatesPresets(): array
    {
        $salesTaxSource = 'https://www.sba.gov/counseling/launch-your-business/department-of-revenue-lookup/';

        return [
            'jurisdiction' => [
                'name' => 'United States Tax (Federal, State & Local)',
                'country_code' => 'USA',
                'region' => 'Multi-level',
                'currency_code' => 'USD',
                'filing_frequency' => 'annual',
                'filing_deadline_days' => 0,
                'tax_authority_name' => 'IRS / State Revenue Authority',
                'registration_threshold' => 0,
                'portal_url' => 'https://www.irs.gov/businesses',
                'metadata' => [
                    'jurisdiction_level' => 'federal_state_local',
                    'regulatory_status' => 'verified_framework',
                    'reviewed_on' => '2026-10-02',
                    'requires_nexus_review' => true,
                    'due_rule' => 'Federal corporate returns are generally due on the 15th day of the fourth month; state and local deadlines vary.',
                    'sources' => ['https://www.irs.gov/instructions/i1120', $salesTaxSource],
                ],
            ],
            'tax_codes' => [
                [
                    'code' => 'USA-FED-CIT-PROVISION',
                    'name' => 'US Federal Corporate Income Tax Provision',
                    'description' => 'Estimated federal C-corporation income tax provision',
                    'type' => 'corporate_income_tax',
                    'category' => 'direct',
                    'rate' => 21,
                    'calculation_method' => 'exclusive',
                    'filing_frequency' => 'annual',
                    'filing_deadline_days' => 0,
                    'report_template' => 'us-form-1120-workpaper',
                    'ledger_payable_account_code' => 'US-FED-TAX-PAYABLE',
                    'ledger_expense_account_code' => 'US-INCOME-TAX-EXPENSE',
                    'applies_to' => ['manual_journal', 'period_close'],
                    'metadata' => [
                        'estimated_only' => true,
                        'requires_configuration' => true,
                        'review_reason' => 'Confirm C-corporation status, taxable-income adjustments, and credits before activation.',
                        'source_url' => 'https://www.irs.gov/instructions/i1120',
                    ],
                ],
                [
                    'code' => 'USA-STATE-SALES',
                    'name' => 'US State Sales Tax',
                    'description' => 'State rate configured for the applicable nexus and destination',
                    'type' => 'sales_tax',
                    'category' => 'indirect',
                    'rate' => 0,
                    'calculation_method' => 'exclusive',
                    'filing_frequency' => 'monthly',
                    'filing_deadline_days' => 0,
                    'report_template' => 'us-state-sales-tax',
                    'ledger_output_account_code' => 'US-SALES-TAX-PAYABLE',
                    'ledger_payable_account_code' => 'US-SALES-TAX-PAYABLE',
                    'applies_to' => ['sales', 'credit_notes'],
                    'metadata' => [
                        'jurisdiction_level' => 'state',
                        'requires_configuration' => true,
                        'requires_nexus_review' => true,
                        'review_reason' => 'Enter the official rate, sourcing method, frequency, and nexus threshold for each registered state.',
                        'source_url' => $salesTaxSource,
                    ],
                ],
                [
                    'code' => 'USA-LOCAL-SALES',
                    'name' => 'US County / City Sales Tax',
                    'description' => 'County, city, district, or other local sales tax',
                    'type' => 'sales_tax',
                    'category' => 'indirect',
                    'rate' => 0,
                    'calculation_method' => 'exclusive',
                    'compound_order' => 20,
                    'filing_frequency' => 'monthly',
                    'filing_deadline_days' => 0,
                    'report_template' => 'us-local-sales-tax',
                    'ledger_output_account_code' => 'US-SALES-TAX-PAYABLE',
                    'ledger_payable_account_code' => 'US-SALES-TAX-PAYABLE',
                    'applies_to' => ['sales', 'credit_notes'],
                    'metadata' => [
                        'jurisdiction_level' => 'local',
                        'requires_configuration' => true,
                        'review_reason' => 'Enter every applicable local component from the official revenue authority.',
                        'source_url' => $salesTaxSource,
                    ],
                ],
                [
                    'code' => 'USA-SALES-EXEMPT',
                    'name' => 'US Sales Tax Exempt',
                    'description' => 'Exempt sale supported by an exemption or resale certificate',
                    'type' => 'sales_tax',
                    'category' => 'indirect',
                    'rate' => 0,
                    'calculation_method' => 'exclusive',
                    'is_exempt' => true,
                    'applies_to' => ['sales'],
                    'metadata' => [
                        'requires_exemption_certificate' => true,
                        'requires_configuration' => true,
                        'review_reason' => 'Verify the customer, product, jurisdiction, certificate number, and expiry.',
                        'source_url' => $salesTaxSource,
                    ],
                ],
            ],
            'withholding_rules' => [
                [
                    'name' => 'US Backup Withholding',
                    'service_type' => 'reportable_payments',
                    'counterparty_type' => 'vendor',
                    'rate' => 24,
                    'threshold_amount' => 0,
                    'account_code' => 'US-WHT-PAYABLE',
                    'payable_account_code' => 'US-WHT-PAYABLE',
                    'receivable_account_code' => 'US-WHT-RECEIVABLE',
                    'certificate_prefix' => 'US-BWH',
                    'metadata' => [
                        'conditional' => true,
                        'review_reason' => 'Apply only when IRS backup-withholding conditions are met; retain W-9 and notice evidence.',
                        'source_url' => 'https://www.irs.gov/businesses/small-businesses-self-employed/backup-withholding',
                        'reviewed_on' => '2026-10-02',
                    ],
                ],
            ],
            'account_mappings' => [
                ['tax_type' => 'sales_tax', 'role' => 'sales_tax_payable', 'account_code' => 'US-SALES-TAX-PAYABLE', 'account_name' => 'US Sales Tax Payable'],
                ['tax_type' => 'withholding', 'role' => 'withholding_payable', 'account_code' => 'US-WHT-PAYABLE', 'account_name' => 'US Backup Withholding Payable'],
                ['tax_type' => 'withholding', 'role' => 'withholding_receivable', 'account_code' => 'US-WHT-RECEIVABLE', 'account_name' => 'US Withholding Receivable'],
                ['tax_type' => 'corporate_income_tax', 'role' => 'tax_payable', 'account_code' => 'US-FED-TAX-PAYABLE', 'account_name' => 'US Federal Income Tax Payable'],
                ['tax_type' => 'corporate_income_tax', 'role' => 'tax_expense', 'account_code' => 'US-INCOME-TAX-EXPENSE', 'account_name' => 'US Income Tax Expense'],
            ],
        ];
    }
}
